config/routes.rb
Rails.application.routes.draw do
  get 'e_token/new'
  resources :e_token
  root :to=>'e_token#new'
  match '/e_token' => 'e_token#create' , via: :Patch
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/e_quotum.rb
class EQuotum < ApplicationRecord
  belongs_to :Places , optional: true
  belongs_to :InstitutionTypes , optional: true
end

app/models/e_token_detail.rb
class ETokenDetail < ApplicationRecord
  belongs_to :Places, optional: true
  belongs_to :Institutions, optional: true
  belongs_to :InstitutionTypes, optional: true
end

app/models/institution.rb
class Institution < ApplicationRecord
	has_many :InstitutionType
end

app/models/institution_type.rb
class InstitutionType < ApplicationRecord
	  belongs_to :Institutions, optional: true
      has_many :Place
end

app/models/place.rb
class Place < ApplicationRecord
  belongs_to :InstitutionTypes, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/e_token_controller.rb
class ETokenController < ApplicationController
  before_action :set_etoken, only: [:show, :edit, :update]

  def index
      @etokendetail = ETokenDetail.all
  end

  def search
  end

  def new
      gon.isButtonClick = false
      @institution = Institution.all
      @institutiontype = InstitutionType.all
      @place =Place.all
      @equotum = EQuotum.all
      @etokendetail = ETokenDetail.new
      defaultValue     
  end

  def show
  end

  def edit
  end

  def destroy
      @taskstatus = ETokenDetail.find(params[:id])
      adjustTokenNoAfterCancel
      @taskstatus.destroy
      defaultValue
      redirect_to(:action=>'new')
  end

  def delete
  end

  def update
  end


  def create      
      gon.isButtonClick = true       
      if params[:SearchToken]
           @etokendetail = ETokenDetail.new(etoken_params)
           defaultValue           
           searchToken
           respond_to do |format|
               format.html { render :new }
               format.json { render json: @etokendetail.errors, status: :unprocessable_entity }
           end
      elsif params[:CancelToken]
          destroy
      else
          @etokendetail = ETokenDetail.new(etoken_params)
          @etokendetail.errors.delete(:all)
          assignToken
          defaultValue
          respond_to do |format|
            if @etokendetail.errors.size == 0
                if @etokendetail.save
                   gon.errorCount = 0
                   gon.ETokenID = @etokendetail.id
                   defaultValue  
                      format.html { render :new}
                      format.json { render json: @etokendetail.errors, status: :unprocessable_entity }
                else
                    gon.errorCount = @etokendetail.errors.size  
                    gon.ETokenID = @etokendetail.id                    
                    format.html { render :new }
                    format.json { render json: @etokendetail.errors, status: :unprocessable_entity }
                end
            else
                gon.errorCount = @etokendetail.errors.size
                gon.ETokenID = @etokendetail.id
                format.html { render :new }
                format.json { render json: @etokendetail.errors, status: :unprocessable_entity }
            end
          end
      end
  end

  private
  def etoken_params   
      params.require(:e_token_detail).permit(:Institutions_id,:InstitutionType_id,:Places_id,:PhoneNo,:Name,:RequestDate)
  end

  private
  def etoken_params_forupdate
      params.permit(:task,:status,:remainder)
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_etoken    
      @etokendetail = ETokenDetail.find(params[:id])
  end

  def defaultValue
    if params[:CancelToken]
      @etokendetail= ETokenDetail.new
    end
    gon.Institution=@etokendetail.Institutions_id
    gon.InstitutionType = @etokendetail.InstitutionType_id
    gon.Place=@etokendetail.Places_id
    gon.PhoneNo =@etokendetail.PhoneNo
    gon.Name =@etokendetail.Name
    gon.ETokenID =@etokendetail.id
  end

  def searchToken
    tomorrowDate = Date.today() + 1
    @equotum = EQuotum.where("Places_id = ?",gon.Place).take 1
    if @equotum.size > 0
      gon.totalToken = @equotum[0].TotalToken
      @totalToken = gon.totalToken
      @usedToken = ETokenDetail.where("Places_id =? and  RequestDate like ?",gon.Place,tomorrowDate).size
      gon.usedToken = @usedToken
      gon.availableToken = gon.totalToken - gon.usedToken
      @availableToken = gon.availableToken
    else
      gon.totalToken=0
      gon.usedToken=0
      gon.availableToken=0
    end
  end

  def assignToken  #find last token no of that place for next day and assign the next TokenNo if available
     tomorrowDate = Date.today() + 1
     @equotum = EQuotum.where("Places_id  = ?",@etokendetail.Places_id).take 1
     @allTokens = ETokenDetail.where("Places_id  = ? and RequestDate like ?",@etokendetail.Places_id,tomorrowDate)
     @allTokens = @allTokens.sort_by {|k| k[:TokenNo] }.reverse

     if(@equotum.size > 0)
        gon.totalToken = @equotum[0].TotalToken
        if(@allTokens.size > 0)
            gon.usedToken =@allTokens.size
            if(@allTokens[0].TokenNo < @equotum[0].TotalToken)
                 lastTokenNo = @allTokens[0].TokenNo
                 if(lastTokenNo == nil)
                        lastTokenNo =0
                 end
                 gon.usedToken =  gon.usedToken + 1
                 @etokendetail.TokenNo =lastTokenNo + 1
                 gon.yourTokenNo =   @etokendetail.TokenNo
                 @etokendetail.RequestDate = tomorrowDate
            else
                  @etokendetail.errors.add(:TokenNo, "All the tokens are over")
            end
        else
            gon.usedToken =1
            gon.yourTokenNo =1
            @etokendetail.TokenNo =1
            @etokendetail.RequestDate = tomorrowDate
        end
        gon.availableToken = gon.totalToken - gon.usedToken
        assignTimming
     end
  end

  def assignTimming
    if gon.yourTokenNo != nil
      totalMinutes = gon.yourTokenNo * 10
      tokenHour = totalMinutes/60
      tokenMinute = totalMinutes % 60
      actualTokenHour = 9 + tokenHour
      if(actualTokenHour >= 12)
        if(actualTokenHour != 12 )
          actualTokenHour = actualTokenHour - 12
        end
        dayType = "PM"
      else
        dayType = "AM"
      end
      gon.tokenTime = actualTokenHour.to_s+":"+tokenMinute.to_s+" "+dayType
    end
  end

  def adjustTokenNoAfterCancel
    tomorrowDate = Date.today() + 1
    @tokenCancel = ETokenDetail.find(params[:id])
    deletingTokenNo =  @tokenCancel.TokenNo
    @tokenToAdjust = ETokenDetail.where(Places_id: @tokenCancel.Places_id,RequestDate:tomorrowDate)
    @tokenToAdjust.each do |item|
    if item.TokenNo > @tokenCancel.TokenNo
      curTokenNo = item.TokenNo.to_f - 1
      item.update_attributes(TokenNo: curTokenNo)
    end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/e_token_helper.rb
module ETokenHelper
end

app/views/e_token/_availableToken.html.erb
<table border="1" cellpadding="0" cellspacing="0">
  <tr>
    <td>
      Total Token
    </td>
    <td>
      Used Token
    </td>
    <td>
      Available Token
    </td>
    <td>
      Your Token
    </td>
    <td>
      Timing to collect Token
    </td>
  </tr>
    <tr class="my_TokenResult" align="center">
    <td>
        <p class ="my_totalToken" align="center"></p>
    </td>
    <td>
      <p class ="my_usedToken" align="center"></p>
    </td>
    <td>
      <p class ="my_availableToken" align="center"></p>
    </td>
      <td>
        <p class ="my_tokenNo" align="center"></p>
      </td>
      <td>
        <p class ="my_timeToCollect" align="center"></p>
      </td>
  </tr>
</table>

app/views/e_token/_form.html.erb
<div align="center">
  <!-- Display all the error Messages -->
  <%= form_for @etokendetail, :url => url_for(:controller => 'e_token', :action => 'create') do |f| %>
      <table>
        <tr>
          <td>
            <ul>
              <%-  @etokendetail.errors.full_messages.each do |msg| %>
                  <li class ="errorMsg" align="left"><p class="my_Error"><%= msg %></p> </li>
              <%- end %>
            </ul>
          </td>
        </tr>
      </table>

      <table border="0">
        <!-- region for Institution dropdown-->
        <tr height="50px">
          <td align="right">
              <%= text_field_tag :id, @etokendetail.id, {:id =>"my_EID" ,class: "my_EID", style:"display: none;"} %>
              <%= f.label "Category" %>
          </td>
          <td align="left">
              <%= f.collection_select :Institutions_id, Institution.order(:InstitutionName), :id,:InstitutionName,{},{class: 'my_Institution'}%>
          </td>
        </tr>

        <!-- region for InstitutionType dropdown-->
        <tr height="40px">
          <td align="right">
              <%= f.label "Category Type" %>
          </td>
          <td align="left">
              <%= f.grouped_collection_select :InstitutionType_id, Institution.order(:InstitutionName), :InstitutionType,:InstitutionName, :id,:InstitutionTypeName,{},{class: 'my_InstitutionType'}%>
          </td>
        </tr>

        <!-- region for Place dropdown-->
        <tr height="40px">
          <td align="right">
              <%= f.label "Place" %>
          </td>
          <td align="left">
              <%= f.grouped_collection_select :Places_id, InstitutionType.order(:InstitutionTypeName), :Place,:InstitutionTypeName, :id,:PlaceName,{},{class: 'my_Place'}%>
          </td>
        </tr>

        <!-- region for Search Token button-->
        <tr height="40px">
          <td align="right">
              <%= f.label "Request Date" %>
          </td>
          <td align="left">
               <%= f.text_field :RequestDate, class:'my_RequestDate'%>
               <%= submit_tag "Search",class:"my_Search" , name: 'SearchToken'%>
          </td>
        </tr>

        <!-- region for Token Detail-->
        <tr>
          <td colspan="2">
            <div class="my_Display">
              <%= render partial: "availableToken", etokendetail: @etokendetail%>
            </div>
          </td>
        </tr>

       <!-- region for Name -->
        <tr height="40px">
          <td align="right">
              <%= f.label "Your Name" %>
          </td>
          <td align="left">
              <%= f.text_field :Name, class:"my_Name"%>
          </td>
        </tr>

        <!-- region for PhoneNo -->
        <tr height="40px">
          <td align="right">
              <%= f.label "Phone No" %>
          </td>
          <td align="left">
              <%= f.text_field :PhoneNo,class:"my_PhoneNo"%>
          </td>
        </tr>

        <!-- region for Request and Cancel Token buttons -->
        <tr height="40px">
          <td></td>
          <td align="left">
             <%= submit_tag "Request Token",class:"my_RequestToken", name: 'CreateToken' %>
             <%= submit_tag "Cancel Token",class:"my_CancelToken", name: 'CancelToken' %>
          </td>
        </tr>

        <!-- region for Request New Token Link -->
        <tr height="40px">
          <td></td>
          <td align="left">
              <div class ="my_CreateNew">
                <%= link_to '|Request New Token|', e_token_new_path %>                    
              </div>
          </td>
        </tr>
     </table>
  <% end%>
</div>

app/views/e_token/index.html.erb
<div align="center"><%= link_to '    |Back to Token|', e_token_new_path %></div>

app/views/e_token/new.html.erb
<%= render partial: "form", etokendetail: @etokendetail%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EToken</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= include_gon %>
  </head>

  <body data-turbolinks="false">
  <br>
  <div align="center"><b>e-Token for Bank and Hospital</b></div>
    <%= yield %>
  </body>
</html>